version: "2.1"

services:
  node:
    image: node:12-alpine
    command: yarn dev:server
    volumes:
      - .:/src
      - ./node_modules:/src/node_modules
    env_file: .env
    working_dir: /src
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
